# This file was generated by GoReleaser. DO NOT EDIT.
cask "bob" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "f1444dd939352f7083277c88ac700f26a5b6f0855553b5ae51e1c0579a191fd5"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02c3d27fa5aab2a1a2a5c445a7d4b738e607fd2cbf41196e22c5cb03dea8e17f"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82db95cedbe052002bc24b47605bffdefb8ddd6e021c6e81c9eb5ba6809e08c5"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "549b0fcddfd05d8f567e827b08d087b00940b0aebbf23cd75a8266a667d19f17"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bob"
  desc "Deterministic repository factory for agent-native developer tools"
  homepage "https://github.com/abdul-hamid-achik/bob"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bob"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bob"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `bob doctor` to inspect required and optional tools. Use `bob plan` before the explicit `bob apply`; launch `bob studio` for a read-only terminal view, or `bob mcp serve` for nine typed repository tools. macOS may require explicit approval for an unsigned build.
  EOS
end
