# This file was generated by GoReleaser. DO NOT EDIT.
cask "bob" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "f38485ec8a693a931b04a8aed68d1ef600b47403505c47005d7f57c954b46fe6"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b70b03bf360729965a26d62d3c47759055548cf86695d2dca5b6520783250102"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "167f339edc6c97306f03c8e0f0275587ea5f37dc13f694abdc57f4acfada71d1"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0dffcbeedccf664b18bc9e00040c07a8ffdd7cffa4f3a28949ea1a0b243b39c"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bob"
  desc "Deterministic repository factory for agent-native developer tools"
  homepage "https://github.com/abdul-hamid-achik/bob"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bob"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bob"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `bob doctor` to inspect required and optional tools. Use `bob plan` before the explicit `bob apply`; launch `bob studio` for a read-only terminal view, or `bob mcp serve` for six typed repository tools. macOS may require explicit approval for an unsigned build.
  EOS
end
