# This file was generated by GoReleaser. DO NOT EDIT.
cask "bob" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "7fb7addbd2eb47ebca2342840a3bcb4bc2c41c58aee26d4a7b21e4b5de50af15"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5f6fb36828541fbbfd46018e1f95574d860e4697d5f2af17ca2c57581ba91f2"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7bf305b06e05fac9fc1c6b44011c6913d07f9b3cf8d281604ae297914c60c5ff"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c27e8a68418d8bb6e881436977a15d81805d6023c1107634085c95febc11d39"
      url "https://github.com/abdul-hamid-achik/bob/releases/download/v#{version}/bob_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bob"
  desc "Deterministic repository factory for agent-native developer tools"
  homepage "https://github.com/abdul-hamid-achik/bob"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bob"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bob"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `bob doctor` to inspect required and optional tools. Use `bob plan` before the explicit `bob apply`; launch `bob studio` for a read-only terminal view, or `bob mcp serve` for nine typed repository tools. macOS may require explicit approval for an unsigned build.
  EOS
end
