# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemap" do
  version "0.47.0"

  on_macos do
    on_intel do
      sha256 "50606e58b195b07e215a195be98ea551a316b6009e6e758ff35659a8e72d5ddb"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "71dfff11fc94d014c5770504d1b903e6c20a0514933a1fc46bcd004b73601079"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fffe4ebb39029dd1c2a68c9cf771513dc01b1db9a2de2c0a14deb70174fd97f0"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1997a35ccb0ee955e352c97efc8b144b24047573cb16745998281e84bd22b86"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codemap"
  desc "Local-first code intelligence: a code graph + semantic search for agents and people"
  homepage "https://github.com/abdul-hamid-achik/codemap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codemap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codemap"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    codemap works offline for structural queries; semantic search is optional and needs a local Ollama (https://ollama.com): run `ollama pull nomic-embed-text`.
  EOS
end
