# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemap" do
  version "0.48.0"

  on_macos do
    on_intel do
      sha256 "6ea8656e0778804fb4a11b9321d4c97ac4c6ad92c713a77c249a43b1ccaeb070"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "965418959198a22de51119a764b04a299907a9ee8207dd59f0d5008a7b0329d4"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "39a4615f13a5bbb4f454a82db5b381fa678831b31eab9ee734eb8afb47e1a5b4"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48095302dd721cf6f8cb17cdfa2ef91906a03078fbb8805bfa0a04826ad58171"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codemap"
  desc "Local-first code intelligence: a code graph + semantic search for agents and people"
  homepage "https://github.com/abdul-hamid-achik/codemap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codemap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codemap"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    codemap works offline for structural queries; semantic search is optional and needs a local Ollama (https://ollama.com): run `ollama pull nomic-embed-text`.
  EOS
end
