# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemap" do
  version "0.58.0"

  on_macos do
    on_intel do
      sha256 "df95839064ad412d77431abe2cce8ec6c83bb2129b45fc096c313c0c2cf4d458"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98823c6e8a1277bc05fdd78278b211e8c165b9b323c4f3213af778bd3380944f"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb10506ce10b98e8321f466ed7dff674cea77b2bd7a7bee93ae02a79fff69085"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dedcf686ca561fb798655606bfcbfaff6ca13273432947d64ee57836b61f7a4c"
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v#{version}/codemap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codemap"
  desc "Local-first code intelligence: a code graph + semantic search for agents and people"
  homepage "https://github.com/abdul-hamid-achik/codemap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codemap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codemap"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    codemap works offline for structural queries; semantic search is optional and needs a local Ollama (https://ollama.com): run `ollama pull nomic-embed-text`.
  EOS
end
