# This file was generated by GoReleaser. DO NOT EDIT.
cask "cortex" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "ec96ea01fbb268e01a826e310b9e52e1ae14209b8338b674b578ea6cf2bb341d"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ef775c519569d054388eb13dae42a745ee24695598697bffe242a7c6cf15b48"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27a1b95b275450cb90aaa062e86d0df7bee582d5292fb139e605387ab4f8f50d"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cbd42beaa997069b97e4ada7f17ffa72685b0d222644f3ae586bc30b70a3e4b8"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cortex"
  desc "Local-first agent kernel: a durable case file + phase machine between an LLM and a specialist tool ecosystem"
  homepage "https://github.com/abdul-hamid-achik/cortex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cortex"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cortex"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `cortex serve` to expose the kernel as an MCP server (8 tools), or use the `cortex` CLI (`--json` for agents). Sibling tools (codemap, vecgrep, cairntrace, glyphrun, fcheap, tvault) are optional — every adapter degrades safely when its binary is absent.
  EOS
end
