# This file was generated by GoReleaser. DO NOT EDIT.
cask "cortex" do
  version "0.15.2"

  on_macos do
    on_intel do
      sha256 "9e76c88c573c239e028f9ee51354469bfcd8ffdf8cc235f3c0aacf35aab5b310"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b739d5d2159ae4e91bef808d8831c7f9c81e80bcc8f11988767e0ec4094ca379"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff8b5d3148cf9c2d377f9a164df29c8a6e26054ff85682eb7429b75b0e255694"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d0332a59386037b4ee4c7b948169e188d7ac6c0c054d291c0e707624acb0ea3"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cortex"
  desc "Local-first agent kernel: a durable case file + phase machine between an LLM and a specialist tool ecosystem"
  homepage "https://github.com/abdul-hamid-achik/cortex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cortex"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cortex"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Git is required for revision-bound verification. Run `cortex serve` for the compact 17-tool agent MCP profile (default), or `cortex serve --profile all` for the full 24-tool operator surface; use the `cortex` CLI for direct operation (`--json` for agents). Sibling tools (bob, codemap, vecgrep, cairn, glyph, fcheap, vidtrace, tvault, veclite) are optional — every adapter degrades safely when its binary is absent.
  EOS
end
