# This file was generated by GoReleaser. DO NOT EDIT.
cask "cortex" do
  version "0.19.0"

  on_macos do
    on_arm do
      sha256 "d6d3d4eb69a5fc16b76a40caac2131c89692c04e07262677c4ff7314f0566a29"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "27be271b04662da831700f12aa0f26d68fde0ec7005833d52aa786d23d810107"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ebb36a9570fa6dc69772f4cc10716fc5beef251839b36e79b61925689822f2d"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8fbf179a953f2a701acd6c71c87017bbccd5de02dbee90930e53deab73fe4ca6"
      url "https://github.com/abdul-hamid-achik/cortex/releases/download/v#{version}/cortex_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cortex"
  desc "Local-first agent kernel: a durable case file + phase machine between an LLM and a specialist tool ecosystem"
  homepage "https://github.com/abdul-hamid-achik/cortex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cortex"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cortex"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Git is required for revision-bound verification. Run `cortex serve` for the compact 17-tool agent MCP profile (default), or `cortex serve --profile all` for the full 24-tool operator surface; use the `cortex` CLI for direct operation (`--json` for agents). Sibling tools (bob, codemap, vecgrep, cairn, glyph, fcheap, vidtrace, tvault, veclite) are optional — every adapter degrades safely when its binary is absent.
  EOS
end
