# This file was generated by GoReleaser. DO NOT EDIT.
cask "fc" do
  name "fc"
  desc "Local file processing CLI and MCP server for images, PDFs, and videos"
  homepage "https://file.cheap"
  version "0.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fc"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_darwin_amd64.tar.gz"
      sha256 "7f8b3a65164b648befdfa6a733c046fef485c02369a784f7e2bc67664844619e"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_darwin_arm64.tar.gz"
      sha256 "b0e0276755502bdc36c1cfa0a0faedf4f4df4da183dfc4654ca1f22f74cc55d7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_linux_amd64.tar.gz"
      sha256 "2e2eddf5283e7bcea1d92d81b03e2bc6a8730e2f1f282b467d436bf60147870e"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_linux_arm64.tar.gz"
      sha256 "bd6cf58c01998b21cc00cd8b49176b239da9762a094dce838beba08850780f19"
    end
  end

  # No zap stanza required
end
