# This file was generated by GoReleaser. DO NOT EDIT.
cask "fc" do
  name "fc"
  desc "Local file processing CLI and MCP server for images, PDFs, and videos"
  homepage "https://file.cheap"
  version "0.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fc"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_darwin_amd64.tar.gz"
      sha256 "31a64ed5ca0d59e5915269cdb69b8953dce74c9f215d03a163c75e1eba3d841c"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_darwin_arm64.tar.gz"
      sha256 "00a40949a25cde0e9cb3c0161e09e2df67ff8303d23efece6f032b2a1bbd43c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_linux_amd64.tar.gz"
      sha256 "653ad8244345d825e16d791a0cd38b8c90ebe0641102651b82d6ef8ea9e6e145"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fc_#{version}_linux_arm64.tar.gz"
      sha256 "0d50c25a763f6ef7a2504eaff00a33d0a32149f00d4e2d4d468ccf6411c53e55"
    end
  end

  # No zap stanza required
end
