# This file was generated by GoReleaser. DO NOT EDIT.
cask "fcheap" do
  version "0.32.1"

  on_macos do
    on_intel do
      sha256 "cf033b2772156e931ac86f5e4267f3f820716596a6be9951d100e7f45ce8e6a2"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "baee75c8a7430ab8d9cc875f5d2ad185f6b270644a10241a67581fde4d5bff85"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b3e40c4e75ac1711b0e148b449577ad2e12babc6cdf69cc38549546ad552ab3"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f454aef59726ccf3a0eaac15cf9c61c6592a9c84840115ba725e49d1b6481ad2"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fcheap"
  desc "The local artifact vault for coding agents"
  homepage "https://github.com/abdul-hamid-achik/file.cheap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fcheap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fcheap"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed with an Apple Developer certificate.
    macOS may show a security warning on first run.

    If macOS blocks the first run, clear quarantine manually:
      xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/fcheap/*/fcheap

    Run `fcheap doctor` after installation to check the stash directory.
  EOS
end
