# This file was generated by GoReleaser. DO NOT EDIT.
cask "fcheap" do
  version "0.24.0"

  on_macos do
    on_intel do
      sha256 "1b8d9ebab2978e922819846ae4210b6bde46d64bff8c012c863bf0fba6655029"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e42e766906d1896bd86bd16a99f9484166e3696ec641a49c92f683a42386743"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae4475f092053b97f033b8e68e41d1ef42b2f57b4322e01ffc0e3818a5abcc39"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "156a9715b500a4f221af662a3d64f68537b90ba1143c3ece744804d326f6595f"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fcheap"
  desc "Local-first stash tool for saving, restoring, compressing, and analyzing files for agent workflows"
  homepage "https://github.com/abdul-hamid-achik/file.cheap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fcheap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fcheap"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed with an Apple Developer certificate.
    macOS may show a security warning on first run.

    If macOS blocks the first run, clear quarantine manually:
      xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/fcheap/*/fcheap

    Run `fcheap doctor` after installation to check the stash directory.
  EOS
end
