# This file was generated by GoReleaser. DO NOT EDIT.
cask "fcheap" do
  version "0.30.0"

  on_macos do
    on_intel do
      sha256 "fb40c490afcc906bd4390a262c0dcf22f9cf6f28095c7c3c506c62bfeb7e30d8"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80e740346f92d4f715dbda320881110b5fe3a556cf0e3e7b3725a7e0e21c92cc"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd6f3e1e85652c4976baaf5fc9ac7bce2a6929a3c0a5049b8467efb8aae6b72a"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f24bd58eb54cbe6762e99c7458569bb587d3122bb21ef8d7bf2c592d40d4aa86"
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v#{version}/fcheap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fcheap"
  desc "The local artifact vault for coding agents"
  homepage "https://github.com/abdul-hamid-achik/file.cheap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fcheap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fcheap"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed with an Apple Developer certificate.
    macOS may show a security warning on first run.

    If macOS blocks the first run, clear quarantine manually:
      xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/fcheap/*/fcheap

    Run `fcheap doctor` after installation to check the stash directory.
  EOS
end
