# This file was generated by GoReleaser. DO NOT EDIT.
cask "glyph" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "3a6b089f073a397ff91f08a4e3718b27ad947f005064c99c797deae27eaf1dbb"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d6334341bf037b800ef5d98897a4101ec19c40ffef2eb892bb49eb3240c4909"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e4100327b06a58de302b48cdb61bb3758ae52e4aa7b7765ad6b04727b5d8b2e"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e0a0a08aa25dcbe8ad32934ff2f52965b84715a0e28a28d87a9b7448a0729cc"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glyph"
  desc "Local-first behavior runner for terminal applications and interactive CLIs"
  homepage "https://github.com/abdul-hamid-achik/glyphrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glyph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glyph"]
    end
  end

  # No zap stanza required

end
