# This file was generated by GoReleaser. DO NOT EDIT.
cask "glyph" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "99fc81487f05c071925da0177fea04b52da4d448f2dc7805629e664b514ce852"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97839ef4a11578101e5f761a869e0eea9d639cda56fe8e8503e2bbd769d9f7bf"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "382e3250b250b99fc06623f11fc8122f316c8e1d17e72bfc8891d3eb29f3f7f1"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f9d05a314c2b0b3f59a8967014a49f8c87e50dea9da5d50f356d12e1ab36740"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glyph"
  desc "Local-first behavior runner for terminal applications and interactive CLIs"
  homepage "https://github.com/abdul-hamid-achik/glyphrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glyph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glyph"]
    end
  end

  # No zap stanza required

end
