# This file was generated by GoReleaser. DO NOT EDIT.
cask "glyph" do
  version "0.14.1"

  on_macos do
    on_intel do
      sha256 "c9ea6aa85bb58a9eafc0d70be152b66e15456ebae7d20635c185d2a1599ff0ea"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54e683598c6ebfbdf5b715b1772fe153bca204be229f5b477038529ab97f9ab9"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71eac6c88386dc3a665defe7ee9bd8192a572356aaece2230d8ba1eedbd3cd0a"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "945320b1e2d027944bc1679ee36bb1e149ad18a21266151975a99cfa924106e7"
      url "https://github.com/abdul-hamid-achik/glyphrun/releases/download/v#{version}/glyph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glyph"
  desc "Local-first behavior runner for terminal applications and interactive CLIs"
  homepage "https://github.com/abdul-hamid-achik/glyphrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glyph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glyph"]
    end
  end

  # No zap stanza required

end
