# This file was generated by GoReleaser. DO NOT EDIT.
cask "hitspec" do
  name "hitspec"
  desc "Plain text API tests. No magic."
  homepage "https://github.com/abdul-hamid-achik/hitspec"
  version "2.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hitspec"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_darwin_amd64.tar.gz"
      sha256 "a5f147ede00723cae753860e32738761c73073ecb933b9b28258e1d72e69c74b"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_darwin_arm64.tar.gz"
      sha256 "bb0400f3f189708ffe09119cd3727c6604ab5fe99d2baff6484f9eaffb2efce7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_linux_amd64.tar.gz"
      sha256 "7c3e2af31fd59c602b0f66de6b84f00ecd9c6040d823d9231e97963b3bc3f0eb"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_linux_arm64.tar.gz"
      sha256 "a925bd8e110d8860aa6b86b7cd1603b37921280737e5227cf4d00d7fd67e266d"
    end
  end

  # No zap stanza required
end
