# This file was generated by GoReleaser. DO NOT EDIT.
cask "hitspec" do
  name "hitspec"
  desc "Plain text API tests. No magic."
  homepage "https://github.com/abdul-hamid-achik/hitspec"
  version "2.19.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hitspec"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_darwin_amd64.tar.gz"
      sha256 "cc17acba5ba6426f6506e8d9b52f803cab46780df0da4ab66ae41823196d4055"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_darwin_arm64.tar.gz"
      sha256 "91642e9e32ac43a8ad0b9421da7b305d9bc5f43c3904aee17b0bfbcb1954e71a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_linux_amd64.tar.gz"
      sha256 "0ab73bc73fe8f12d1f219071ad00ca575db0615e99a804d4539f21c9e4f5a408"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v#{version}/hitspec_#{version}_linux_arm64.tar.gz"
      sha256 "b01297409340470eef960c5d696106a0fdec85cc0381f48cb8e5476e9de701cb"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hitspec"] if OS.mac?
  end

  # No zap stanza required
end
