# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-agent" do
  version "0.29.0"

  on_macos do
    on_intel do
      sha256 "291fda9c5b6ae41b446f12e5ef66f30b2b92bbdaf299cbda7e6f246a95f421f8"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4506be31789e4285ce32200bbc56d6e7d7a834a21bbda85eb1562e019cd30680"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f40bfcf1e508e58d6174711b37793594888c36ea27df4ca15270eec1084b8ed9"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d663e27f6d97fdf33f5e7de76175a59c377dccb178da22f8bfbe9e21dddf1a7"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "local-agent"
  desc "Local AI agent with TUI, powered by Ollama and MCP servers"
  homepage "https://github.com/abdul-hamid-achik/local-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-agent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-agent"] if OS.mac?
  end

  # No zap stanza required

end
