# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-agent" do
  version "0.27.2"

  on_macos do
    on_intel do
      sha256 "081940c8403f1c54277bb5a384129f59db42ca9cb2458193cf889bb1b93c424c"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f20fd471579917ffef9a761c6b48085d11536d0832269c3a17b8ae1a62cfc846"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "041b88939bc49d30340df2934326fd3a9554c18c7a36a23bb7a8407f9c09bae1"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb949abc95b9ab660cb5c1c4aa6d08e109307a04312e7eaec7b8e69ac13a0dd0"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "local-agent"
  desc "Local AI agent with TUI, powered by Ollama and MCP servers"
  homepage "https://github.com/abdul-hamid-achik/local-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-agent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-agent"] if OS.mac?
  end

  # No zap stanza required

end
