# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-agent" do
  version "0.21.0"

  on_macos do
    on_intel do
      sha256 "c74fcac36764887bb1345840c80afc28c456128ed6ff761930fb61efff7684cd"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15be77f8e33e10cc4c9b1891237037cb4dde3f1affd6f88c86b8632bf11398a1"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db2e5c68b51eab741f7d2d24331c36936fc127a780102323ff4378ce143874be"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "338203cd54cfff9395a099970872f92e79f38d060bb7e2ab00527111bfb76235"
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v#{version}/local-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "local-agent"
  desc "Local AI agent with TUI, powered by Ollama and MCP servers"
  homepage "https://github.com/abdul-hamid-achik/local-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-agent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-agent"] if OS.mac?
  end

  # No zap stanza required

end
