# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcphub" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "054d6d407b7f3f3017cf5944bf00c88a0cad3300943adcb759d470b6450a9ba7"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2a685cf9746e7371a49f11b1172224a3f9942a2412930f30906f9931fac66975"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ea6c64c3e9b8f54383d53c8621e89088d02dcfc34946c6aad0a4419b39b9fa1d"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d696e27bd807c601da08bb1102039817bae24e8445175d6768ac2139f5bbf01d"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "mcphub"
  desc "One hub for all your MCP servers, synced into every agent"
  homepage "https://github.com/abdul-hamid-achik/mcphub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcphub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcphub"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point your agents at `mcphub mcp serve` (gateway mode) or run `mcphub studio` to manage servers. See `mcphub --help`.
  EOS
end
