# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcphub" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "02d1e7b6c7c55fda1429cf449bf103e4a72dde22661110786f1c5a43957cb784"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b2b61c0e250798327201230276bc51c829334917f58ace121c911e5925ac1bd0"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8d5b3e8e64a493160c7242bfdbdb1eddb5132fb4c2242a472d66bfaacfe26a39"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "197d6fc2b6fc7a5a59c7a0d294f3c796b66e9f2f1d247bbe250423eb432bca4d"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "mcphub"
  desc "One hub for all your MCP servers, synced into every agent"
  homepage "https://github.com/abdul-hamid-achik/mcphub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcphub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcphub"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point your agents at `mcphub mcp serve` (gateway mode) or run `mcphub studio` to manage servers. See `mcphub --help`.
  EOS
end
