# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcphub" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "91637532eadd7afac9a210af5c284efb4771950e8e448df4857f531a8a13b1ed"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7532e6528288b47c6cce734ea19e82898250cf2d03a68e78f2bc7dd9b113dc70"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a7512ffd58d3f9525f1e7c9a807d89ba75f39884f1a788478bb9af45f0e5bf1b"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "10e0f4dbaa46cabbcb9f84c6e262e1c5e8dd15539b1c8830fbebec552915a132"
      url "https://github.com/abdul-hamid-achik/mcphub/releases/download/v#{version}/mcphub_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "mcphub"
  desc "One hub for all your MCP servers, synced into every agent"
  homepage "https://github.com/abdul-hamid-achik/mcphub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcphub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcphub"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point your agents at `mcphub mcp serve` (gateway mode) or run `mcphub studio` to manage servers. See `mcphub --help`.
  EOS
end
