# This file was generated by GoReleaser. DO NOT EDIT.
cask "minerva" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "d42a46f3b9e06513ccf13e13f5a6f3333cbb074f277112b192c2038751a8ca37"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "08c46b56aab10887b4b82944213107604209b7cb91c81d699ad7dad47e8b780c"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa9ab0f80705c591ab47d028963da717a3b70a7915384a959ac9bf883f63196f"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f18948131165805f1465ad2dbf004142ee27aa04b4f97d9a8578c9f20bacc2f5"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_linux_arm64.tar.gz"
    end
  end

  name "minerva"
  desc "Skill intelligence for agent harnesses — propose SKILL.md from session traces and sync libraries"
  homepage "https://minervacli.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "minerva"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/minerva"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `minerva init` to create ~/.agents/skills, then `minerva propose` to draft skills from harness sessions.
  EOS
end
