# This file was generated by GoReleaser. DO NOT EDIT.
cask "minerva" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "8a8f8c9257a83f2ee801352ca0eac591fbca881f0bd1dc8cb1f84c46bccea36d"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f4af8ff43b55a86735abd90e02a7cd6f082ca956394631dfcc30a24412c4747"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd5a2cc13cfab765625e96924ba0319a00d6e06e2eb18072648745d8c3da06e2"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "96c008ec1094d32cd14cd3b12aa37c8b3c47f6f081bc92aa17d7414e44b9dc7e"
      url "https://github.com/abdul-hamid-achik/minerva/releases/download/v#{version}/minerva_#{version}_linux_arm64.tar.gz"
    end
  end

  name "minerva"
  desc "Skill intelligence for agent harnesses — propose SKILL.md from session traces and sync libraries"
  homepage "https://minervacli.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "minerva"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/minerva"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `minerva init` to create ~/.agents/skills, then `minerva propose` to draft skills from harness sessions.
  EOS
end
