# This file was generated by GoReleaser. DO NOT EDIT.
cask "monitor" do
  version "1.13.0"

  on_macos do
    on_intel do
      sha256 "7c8ccdf2ac2b0e1754935886c0380bb7601443cbc837cbced54c15907f2aa81a"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bb5285afb35f3bab327878004ef8623166585807ceb975f3f0b4771733a82674"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3bd09f1945ed8d4a4854a39c430c0c37ced696f5c0138f3e466ebd4518d4f677"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f49192ff07505e63ead504520cc40d165801a3671bd42da613a4e8f8aee2d392"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "monitor"
  desc "Local-first agent-harnessable observability tool for macOS"
  homepage "https://github.com/abdul-hamid-achik/monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monitor"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    monitor works offline for system/process metrics; real temperature readings require sudo powermetrics (optional).
  EOS
end
