# This file was generated by GoReleaser. DO NOT EDIT.
cask "monitor" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "7181bc687129e7d81bc1a68e31af2d3b2bbbee8711f4e75ef014db3cdef553b7"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ff5d41efb760af2f8927d94f3c6c9b6cff132e382d354adb8fe2eb1b7fbcc482"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e427feb3e7a6cee39a0f2a693ee6bf79937f63135f4c16e1c33624d323ce1a4f"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "07a8fe57a361e4e6d2b4985751f6972b8508a2e63d41315475e21072678ba4cc"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "monitor"
  desc "Local-first agent-harnessable observability tool for macOS"
  homepage "https://github.com/abdul-hamid-achik/monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monitor"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    monitor works offline for system/process metrics; real temperature readings require sudo powermetrics (optional).
  EOS
end
