# This file was generated by GoReleaser. DO NOT EDIT.
cask "monitor" do
  version "1.15.1"

  on_macos do
    on_intel do
      sha256 "b327a67f908b4448be8a025b2494395b01f945898f2a35f35d8578d6bc22607d"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b29d8ee70af0ccdc6c0a1ae3f8ae7eb209088d4abf4e872d3ad9a83f746f65ba"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "636e4a1a8718d94c66fd18544e322fb3e69d3330393ed977104d70854726f893"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7f820a766e0a4f8e47a2e0cce1e7fe7a6387729aa482630cb81ffa56e1afe659"
      url "https://github.com/abdul-hamid-achik/monitor/releases/download/v#{version}/monitor_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "monitor"
  desc "Local-first agent-harnessable observability tool for macOS"
  homepage "https://github.com/abdul-hamid-achik/monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monitor"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    monitor works offline for system/process metrics; real temperature readings require sudo powermetrics (optional).
  EOS
end
