# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuimark" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "18c5a773cc4f6a2dc26ee058e0c56927eb3c0483be168e300ebfa1d6c0eb02f9"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "aa05bb205e7013a407bd9e11b3954cb1a817fad5636ca25b6d29c4b03b4f8762"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af3f229e8fb3e57a7e55f8ff4a9095c2aac35ec3e256c0e03ec0c6e4efa78867"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "da4e1c1c91ce426dde5abdc0789073c1f9e987cb467dafb7a2d78c895f4058ce"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "tuimark"
  desc "Declarative view language for terminal UIs (.tui markup, .tcss styles)"
  homepage "https://github.com/abdul-hamid-achik/tuimark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuimark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuimark"]
    end
  end

  # No zap stanza required

end
