# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuimark" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "dc7dd4e8e4a03cba886cb568c186aaa5574ade645e726e9b919db1c9b824dba9"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bab0406def6ef989a49764fa38379f7521604e745bb425bc4f020a368d97b851"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d24fc14a227d0a4efe8d1a80096008473bf872718c8fed90be845131f391c836"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "761fc19c20ed6b4536448824639a14e7aed6ae5a4e7b30526818beeddcb9efbc"
      url "https://github.com/abdul-hamid-achik/tuimark/releases/download/v#{version}/tuimark_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "tuimark"
  desc "Declarative view language for terminal UIs (.tui markup, .tcss styles)"
  homepage "https://github.com/abdul-hamid-achik/tuimark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuimark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuimark"]
    end
  end

  # No zap stanza required
end
