# This file was generated by GoReleaser. DO NOT EDIT.
cask "tvault" do
  version "0.20.2"

  on_macos do
    on_intel do
      sha256 "b93ed8c0c04ff71af8452dad75d2f28fbdbecb0dc87ca473f39007565af45e27"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "74590c5ecc5503fc9166f0e6c2e3d6d7196e669630dec9b32dd9e48284265881"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3c5f6b9fa565df32d02c1905ec3e1089182a54157b3eb59e94f46142ec1285d"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4ccf474bc94d8ce7ed496851f92110e45e334a2ef9df009d25a9cc45410267e"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tvault"
  desc "Dead simple secrets management CLI and MCP server"
  homepage "https://github.com/abdul-hamid-achik/tinyvault"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tvault"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tvault"]
    end
  end

  # No zap stanza required

end
