# This file was generated by GoReleaser. DO NOT EDIT.
cask "tvault" do
  version "0.17.1"

  on_macos do
    on_intel do
      sha256 "8f3afec167b06adca8bd8d961faf895a5010d7582eaf37ba3d658538a1b63527"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "43e680a3935fc23664a6ff68f83ec610c70e12e9b2af7767cc83447cc214ec90"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2764d4e6becf56ea91b0f159f29a0d9b663c82206461ea6f5e5305e2d71f0ad4"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eafe08155d8aa4728d57c356a22d2c06f7c3f59bcb17d51a3a7d154c3c90870e"
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v#{version}/tvault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tvault"
  desc "Dead simple secrets management CLI and MCP server"
  homepage "https://github.com/abdul-hamid-achik/tinyvault"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tvault"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tvault"]
    end
  end

  # No zap stanza required

end
