# This file was generated by GoReleaser. DO NOT EDIT.
cask "vecai" do
  name "vecai"
  desc "AI-powered codebase assistant with semantic search and Claude intelligence"
  homepage "https://github.com/abdul-hamid-achik/vecai"
  version "0.22.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vecai"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_darwin_amd64.tar.gz"
      sha256 "f1ae471f5212157e22a32281801036c859fd5c8febf10d8f6190ee1d4a1c5926"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_darwin_arm64.tar.gz"
      sha256 "aa5753adbb3e6e8de380ab6f1f91034f7622f74deab72c45df41861cd2c1c42b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_linux_amd64.tar.gz"
      sha256 "1a130cdc2e59f90d45b66323e036091a4c762d266085ba0196d48b825ac2fa74"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_linux_arm64.tar.gz"
      sha256 "221a1e346587cf0467234560c55ff11fec01c4557d3c5ab5fb07446a62ccdc03"
    end
  end

  # No zap stanza required
end
