# This file was generated by GoReleaser. DO NOT EDIT.
cask "vecai" do
  name "vecai"
  desc "AI-powered codebase assistant with semantic search and Claude intelligence"
  homepage "https://github.com/abdul-hamid-achik/vecai"
  version "0.20.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vecai"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_darwin_amd64.tar.gz"
      sha256 "be9e325885a7cfbf2a3006d305ad794a0bd640e483b02d567326ccb687ffb6dd"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_darwin_arm64.tar.gz"
      sha256 "edeb126b2aaa8ca3630b675df06ef9c4db49a06cac3e7aea8c30fbff3c18cba4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_linux_amd64.tar.gz"
      sha256 "aee678870222d64dad9cc6d5cced7854a46afaf3bf0f572721c6501d1c5c3027"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/vecai/releases/download/v#{version}/vecai_#{version}_linux_arm64.tar.gz"
      sha256 "af3f9ef74b91a6464dd8b730811bbf3af95d8c68fca8960614c05548df26f51b"
    end
  end

  # No zap stanza required
end
