# This file was generated by GoReleaser. DO NOT EDIT.
cask "veclite" do
  version "0.24.0"

  on_macos do
    on_intel do
      sha256 "9c3187f4bf8aafa9f3671fe7ef6e9032066f6cb2fdeba05b468cf4252c96770c"
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v#{version}/veclite_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30117191db64ef7fe1782325ee4b5c3ecf29281123dc95ce253c0bdae0a5a978"
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v#{version}/veclite_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65404739655d05697a8bf9efb98a01b28d391a7c05537cd4c94bf3c6df818789"
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v#{version}/veclite_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ade401b843647809845bfc28dd3761f1ec7832269cfee77243aa95dfe929b32"
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v#{version}/veclite_#{version}_linux_arm64.tar.gz"
    end
  end

  name "veclite"
  desc "SQLite for vectors. Embed anywhere, no servers, one file"
  homepage "https://github.com/abdul-hamid-achik/veclite"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "veclite"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/veclite"] if OS.mac?
  end

  # No zap stanza required

  caveats <<~EOS
    The veclite binary is not Apple-notarized; this cask clears its quarantine attribute during installation.
  EOS
end
