# This file was generated by GoReleaser. DO NOT EDIT.
cask "vidtrace" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "d23bcf608fdb0d274e199b6e3060a660f0f2e1c78174b0eedd756e52dbaf8ab4"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9a0a0f1704d5632bed817320e96f85114f3b20ee0cd86056d1c1928a2d58902"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66a54402bd4b18ecb1541b1623b9ac939e2740169a8eb1febc2989d13efac293"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f96d428c99c94551d8e716925173f90fd35ee0799d4402cb097c5033a580a234"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vidtrace"
  desc "Turn bug videos into timestamped evidence bundles for humans and coding agents"
  homepage "https://github.com/abdul-hamid-achik/vidtrace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vidtrace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vidtrace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed with an Apple Developer certificate.
    macOS may show a security warning on first run.

    If macOS blocks the first run, clear quarantine manually:
      xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/vidtrace/*/vidtrace

    Run `vidtrace doctor` after installation to check ffmpeg, ffprobe, tesseract, and whisper.
  EOS
end
