# This file was generated by GoReleaser. DO NOT EDIT.
cask "vidtrace" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "402d9750ce81491e12cbe5e14e70a2a6bf8b585cc08e2930c4f19208692eca12"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f13ac86cc49b991b6bced3f992594629ab7a5aba5f74173dfb0b9108950ffad"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6dad38422d4aeba49598ad238fc6b1f370cf82743bfc1a328510a0206695d67f"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6ff7a03c0dc27215ca07b0b3e086941a94e8f9a8f68b17bff734171bdc8e6a0"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vidtrace"
  desc "Turn bug videos into timestamped evidence bundles for humans and coding agents"
  homepage "https://github.com/abdul-hamid-achik/vidtrace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vidtrace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vidtrace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed with an Apple Developer certificate.
    macOS may show a security warning on first run.

    If macOS blocks the first run, clear quarantine manually:
      xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/vidtrace/*/vidtrace

    Run `vidtrace doctor` after installation to check ffmpeg, ffprobe, tesseract, and whisper.
  EOS
end
