# This file was generated by GoReleaser. DO NOT EDIT.
cask "vidtrace" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ebfb6c854afa814d20cb1c826d8eb78d219167a4d60ee7fd9fc9cd731a58ad25"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fc681d71547cf3ebd847957ac44b4e475c336063f7ba1aebb8a02c486e2eec1"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0707ad95da7b1c5252f38beaf5389287d157e316423b617c688a789f89e3bca"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b912ab7d013201ed6b8beff1b04f7c57b9db0319c4370c637438b75a762e967"
      url "https://github.com/abdul-hamid-achik/vidtrace/releases/download/v#{version}/vidtrace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vidtrace"
  desc "Turn bug videos into timestamped evidence bundles for humans and coding agents"
  homepage "https://github.com/abdul-hamid-achik/vidtrace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vidtrace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vidtrace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed with an Apple Developer certificate.
    macOS may show a security warning on first run.

    If macOS blocks the first run, clear quarantine manually:
      xattr -dr com.apple.quarantine /opt/homebrew/Caskroom/vidtrace/*/vidtrace

    Run `vidtrace doctor` after installation to check ffmpeg, ffprobe, tesseract, and whisper.
  EOS
end
