# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "Blueprint language toolchain — compile .bp files to TypeScript/Node.js projects"
  homepage "https://github.com/abdul-hamid-achik/blueprint"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.1.0/bp_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "ae8a38cff56ab2951171691f2f1937fb278925c780efe6941a0934cff84d44e4"

      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.1.0/bp_0.1.0_Darwin_arm64.tar.gz"
      sha256 "51e99f8f6c3a7a9e90279e5063070ea46a4f8940d7c276d55dd7984c0eef2027"

      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.1.0/bp_0.1.0_Linux_x86_64.tar.gz"
      sha256 "6eb97740e51019dc81d35a129e17f037d8069cf60f59f00bbf9370c16a626cc4"
      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.1.0/bp_0.1.0_Linux_arm64.tar.gz"
      sha256 "7d3554e5eab24831cff0e85179da95784e473716a84d7fc9877506a46b4bc00b"
      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  test do
    system "#{bin}/bp", "version"
  end
end
