# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "Blueprint language toolchain — compile .bp files to TypeScript/Node.js projects"
  homepage "https://github.com/abdul-hamid-achik/blueprint"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.3.5/bp_0.3.5_Darwin_x86_64.tar.gz"
      sha256 "a38f3d362f7154f7950059757022c9be205bbfcce15818c3558ed68eb2118497"

      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.3.5/bp_0.3.5_Darwin_arm64.tar.gz"
      sha256 "5d758181e5c724931293b50a5ebd3d867139fe79d7716209e6af819fe87cb6a8"

      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.3.5/bp_0.3.5_Linux_x86_64.tar.gz"
      sha256 "8b3c7590c071c6f0f9b2426d36fee3294b2a50798ec20919099c76fa4e47ec5f"
      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/blueprint/releases/download/v0.3.5/bp_0.3.5_Linux_arm64.tar.gz"
      sha256 "629a8f8a3855240ad65c8e209d962ef794448484e226dd9223910dad830f7065"
      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  test do
    system "#{bin}/bp", "version"
  end
end
