# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemap < Formula
  desc "Local-first code intelligence: a code graph + semantic search for agents and people"
  homepage "https://github.com/abdul-hamid-achik/codemap"
  version "0.8.0"
  license "MIT"

  depends_on "ollama" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v0.8.0/codemap_0.8.0_darwin_amd64.tar.gz"
      sha256 "af7afdd8952188cf9fe3b7da028dab8fc296238d5e02ef7b511ce0e1ee54d170"

      define_method(:install) do
        bin.install "codemap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v0.8.0/codemap_0.8.0_darwin_arm64.tar.gz"
      sha256 "01cfb10c3415d198c190de73224f3bf999b999442e324a6d33d313cc04612f39"

      define_method(:install) do
        bin.install "codemap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v0.8.0/codemap_0.8.0_linux_amd64.tar.gz"
      sha256 "aa59b836eac478bb7cf6d638e91285a38ee19b3ccd8b76e06d7a97a4abace3ee"
      define_method(:install) do
        bin.install "codemap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/codemap/releases/download/v0.8.0/codemap_0.8.0_linux_arm64.tar.gz"
      sha256 "3e194732725243f4485641423bd41367978010513a7d61ef19f8d140fa556e84"
      define_method(:install) do
        bin.install "codemap"
      end
    end
  end

  test do
    system "#{bin}/codemap", "--version"
  end
end
