# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fc < Formula
  desc "CLI for file.cheap - upload, transform, and deliver images"
  homepage "https://file.cheap"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v0.2.1/fc_0.2.1_darwin_amd64.tar.gz"
      sha256 "64b578738bc927c056ba602d8cc57403e37f462ea8349adc123346c865ab81de"

      def install
        bin.install "fc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v0.2.1/fc_0.2.1_darwin_arm64.tar.gz"
      sha256 "c110ea70533f34dad570eb2b0a52f26cf6ef4792084decc4e47c246f4cbf1f50"

      def install
        bin.install "fc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v0.2.1/fc_0.2.1_linux_amd64.tar.gz"
      sha256 "5bddf77fad0bd45ee2f8d6358f859d90bc766ed0ec70dfd357693bc35dbdfc56"
      def install
        bin.install "fc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/file.cheap/releases/download/v0.2.1/fc_0.2.1_linux_arm64.tar.gz"
      sha256 "d2e924591884d0d8006b26bcca9baa0f153a0458c36190bf2d98d466e120f514"
      def install
        bin.install "fc"
      end
    end
  end

  test do
    system "#{bin}/fc", "--version"
  end
end
