# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpeek < Formula
  desc "TUI for code review, git visualization, and repository management"
  homepage "https://github.com/abdul-hamid-achik/gpeek"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.1/gpeek_0.3.1_darwin_amd64.tar.gz"
      sha256 "7eba0eaf1182de1f973bfa4238271e59d5df8b0392a4971d25e220968d5bb706"

      def install
        bin.install "gpeek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.1/gpeek_0.3.1_darwin_arm64.tar.gz"
      sha256 "67048c7d44f7f3d8d722ac39e248b1e71bf28ea4e24a2510c12679f601d7a852"

      def install
        bin.install "gpeek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.1/gpeek_0.3.1_linux_amd64.tar.gz"
      sha256 "ca84291e606c7d20cc799da98afa9befe23353225d6ad40770028161e43dec03"
      def install
        bin.install "gpeek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.1/gpeek_0.3.1_linux_arm64.tar.gz"
      sha256 "ce433a38425a5898495d3176820b7415c6cb0b237f07dbc6a5afcc1587ab37fe"
      def install
        bin.install "gpeek"
      end
    end
  end

  test do
    system "#{bin}/gpeek", "--version"
  end
end
