# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpeek < Formula
  desc "TUI for code review, git visualization, and repository management"
  homepage "https://github.com/abdul-hamid-achik/gpeek"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.4/gpeek_0.3.4_darwin_amd64.tar.gz"
      sha256 "99223622c5508e7ced23b53035309b75d5ec4e068165a81d8a02066333104cf4"

      def install
        bin.install "gpeek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.4/gpeek_0.3.4_darwin_arm64.tar.gz"
      sha256 "f912321bd7065645f52d71a28aafd6000164c8f49842ff5dfc7c7fec8b525ec1"

      def install
        bin.install "gpeek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.4/gpeek_0.3.4_linux_amd64.tar.gz"
      sha256 "86fd46e11459622165f9f11dc8d111b72b45c3ff660ace4c38cc21d367bbbf9c"
      def install
        bin.install "gpeek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/gpeek/releases/download/v0.3.4/gpeek_0.3.4_linux_arm64.tar.gz"
      sha256 "e3580e664e1c06a2cad54ae552d054b1fda34ba27cd4424e1400635133af5f12"
      def install
        bin.install "gpeek"
      end
    end
  end

  test do
    system "#{bin}/gpeek", "--version"
  end
end
