# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hitspec < Formula
  desc "Plain text API tests. No magic."
  homepage "https://github.com/abdul-hamid-achik/hitspec"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.0/hitspec_2.0.0_darwin_amd64.tar.gz"
      sha256 "f19b1617b8b90ba72049c3a2259ea060fcfa52aa02c3181e155cabd672084880"

      def install
        bin.install "hitspec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.0/hitspec_2.0.0_darwin_arm64.tar.gz"
      sha256 "61712792d0353917f2ab4d0de2917b4ea8ce5a3020f9943e9c8c509b369d9e13"

      def install
        bin.install "hitspec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.0/hitspec_2.0.0_linux_amd64.tar.gz"
      sha256 "640e25028889be193eeb27f0733ce2dbe3bbf3a07585173f5e8b43f6b4465e03"
      def install
        bin.install "hitspec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.0/hitspec_2.0.0_linux_arm64.tar.gz"
      sha256 "65cf71b161b62703dc15b0c894254dcf897556a6cb12d95740d2594366f75702"
      def install
        bin.install "hitspec"
      end
    end
  end

  test do
    system "#{bin}/hitspec", "version"
  end
end
