# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hitspec < Formula
  desc "Plain text API tests. No magic."
  homepage "https://github.com/abdul-hamid-achik/hitspec"
  version "2.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.7.0/hitspec_2.7.0_darwin_amd64.tar.gz"
      sha256 "664196ffdaa046e93fbd2b349db2be9e6d2d3e9a11ff081d0a1f6f0ccba0c960"

      def install
        bin.install "hitspec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.7.0/hitspec_2.7.0_darwin_arm64.tar.gz"
      sha256 "de980af5be9993f3c8c077176ccd0d6049fbc5a937f490c3534b7dcea6365317"

      def install
        bin.install "hitspec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.7.0/hitspec_2.7.0_linux_amd64.tar.gz"
      sha256 "3fcc892403f6b18fc5c0c57a1c21fa204fb79b9b62be0139b7e07ef548a1eb1f"
      def install
        bin.install "hitspec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.7.0/hitspec_2.7.0_linux_arm64.tar.gz"
      sha256 "b0343b0b3ead2bd2288aa91bdce64e8b8afa8838e76a34dc5e761d28647722ba"
      def install
        bin.install "hitspec"
      end
    end
  end

  test do
    system "#{bin}/hitspec", "version"
  end
end
