# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hitspec < Formula
  desc "Plain text API tests. No magic."
  homepage "https://github.com/abdul-hamid-achik/hitspec"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.2/hitspec_2.0.2_darwin_amd64.tar.gz"
      sha256 "debb549097a0d69e8dd4ad2bb00021a7b52602bf635ef47c986d92522a249c5f"

      def install
        bin.install "hitspec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.2/hitspec_2.0.2_darwin_arm64.tar.gz"
      sha256 "447400ffd933f3a254e61b212482c6db17d0159b3e9b69651ea41a2584e986f5"

      def install
        bin.install "hitspec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.2/hitspec_2.0.2_linux_amd64.tar.gz"
      sha256 "0b2d9a538b4e314ee5862598acecc912732df48b6f242c89dc1ceb7f64a78938"
      def install
        bin.install "hitspec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/hitspec/releases/download/v2.0.2/hitspec_2.0.2_linux_arm64.tar.gz"
      sha256 "87c7263fe81b0f517a212c123185a2863c93193e44ea67d77aaca38cc5d54e05"
      def install
        bin.install "hitspec"
      end
    end
  end

  test do
    system "#{bin}/hitspec", "version"
  end
end
