# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalAgent < Formula
  desc "Local AI agent with TUI, powered by Ollama and MCP servers"
  homepage "https://github.com/abdul-hamid-achik/local-agent"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.13.1/local-agent_0.13.1_darwin_amd64.tar.gz"
      sha256 "4a6cba146185d998852e7a45814bf5f644305456ea2215bae57dfce23d85729b"

      define_method(:install) do
        bin.install "local-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.13.1/local-agent_0.13.1_darwin_arm64.tar.gz"
      sha256 "e4cbc06bb773ca9601fce20e07bd6cc6156cf2946289ebce6c08fffe36e7a582"

      define_method(:install) do
        bin.install "local-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.13.1/local-agent_0.13.1_linux_amd64.tar.gz"
      sha256 "3fcd6dbcbe7b312785ac51a4dc6a7c3157e87a59b7e3070162ea4c39830ed9a1"
      define_method(:install) do
        bin.install "local-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.13.1/local-agent_0.13.1_linux_arm64.tar.gz"
      sha256 "caf6806ec0e157ae53e325db2e1a08371a2433a31a50f3c616141d9d3e8b8de5"
      define_method(:install) do
        bin.install "local-agent"
      end
    end
  end

  test do
    system "#{bin}/local-agent", "--version"
  end
end
