# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalAgent < Formula
  desc "Local AI agent with TUI, powered by Ollama and MCP servers"
  homepage "https://github.com/abdul-hamid-achik/local-agent"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.5.1/local-agent_0.5.1_darwin_amd64.tar.gz"
      sha256 "41f03b19e88984f4083db5af3fb138ec671bbd36355ba5d8ddc7fe75309d62e5"

      define_method(:install) do
        bin.install "local-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.5.1/local-agent_0.5.1_darwin_arm64.tar.gz"
      sha256 "2a77862b1d18aa9980859d64b6cd487d9a85e4faeb0d3e70483e7d6f2b37bc86"

      define_method(:install) do
        bin.install "local-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.5.1/local-agent_0.5.1_linux_amd64.tar.gz"
      sha256 "e81ce72a8e246c0498732187cbb1b86719df366c857788b91bf18be4dfdc6471"
      define_method(:install) do
        bin.install "local-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/local-agent/releases/download/v0.5.1/local-agent_0.5.1_linux_arm64.tar.gz"
      sha256 "7697b703c06f64488c6b550827d548e5e5fb20ead34f0a8754b02edf51465db0"
      define_method(:install) do
        bin.install "local-agent"
      end
    end
  end

  test do
    system "#{bin}/local-agent", "--version"
  end
end
