# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monitor < Formula
  desc "Terminal-based system monitor for macOS (Apple Silicon) built with Go"
  homepage "https://github.com/abdul-hamid-achik/monitor"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/abdul-hamid-achik/monitor/releases/download/v0.2.0/monitor_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "949e849fd193b8ee0e2b418f8e84e8a9928331241785cf3fd947a7b7ea3954bf"

    define_method(:install) do
      bin.install "monitor"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/abdul-hamid-achik/monitor/releases/download/v0.2.0/monitor_0.2.0_Darwin_arm64.tar.gz"
    sha256 "32a0cb594031616bd60716275d5a9ce17298ca56d19facb356def46263e1d956"

    define_method(:install) do
      bin.install "monitor"
    end
  end

  test do
    system "#{bin}/monitor", "--version"
  end
end
