# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monitor < Formula
  desc "Terminal-based system monitor for macOS (Apple Silicon) built with Go"
  homepage "https://github.com/abdul-hamid-achik/monitor"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/abdul-hamid-achik/monitor/releases/download/v0.1.0/monitor_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "a384de045a2ddbd0b892c91ade96608f65299a62284c8092dcf26c9259e6aaec"

    define_method(:install) do
      bin.install "monitor"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/abdul-hamid-achik/monitor/releases/download/v0.1.0/monitor_0.1.0_Darwin_arm64.tar.gz"
    sha256 "24d30e24429028fa66a30655d30deb1ce5f7e2f69cf26097d3242fff140edbae"

    define_method(:install) do
      bin.install "monitor"
    end
  end

  test do
    system "#{bin}/monitor", "--version"
  end
end
