# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noted < Formula
  desc "A CLI knowledge base to store and manage your notes efficiently"
  homepage "https://github.com/abdul-hamid-achik/noted"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.6.0/noted_0.6.0_darwin_amd64.tar.gz"
      sha256 "2c942765edd46cd2525ddd07ee54e354ee2ca15c42acbe60a4ed4a0d769d58df"

      def install
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.6.0/noted_0.6.0_darwin_arm64.tar.gz"
      sha256 "854397b76c302ebdcf5523e3198205a4e3c6eb7a3ffdcdebcd85c5d3a035c38b"

      def install
        bin.install "noted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.6.0/noted_0.6.0_linux_amd64.tar.gz"
      sha256 "66f2d0c27181d7d21cb64ada399ea3ef4451f68c602d44590d4c3565df54dca9"
      def install
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.6.0/noted_0.6.0_linux_arm64.tar.gz"
      sha256 "2421fce8f51307eef1cc95001145f8e44a5c74d6ec81c88098fb452c3274ede5"
      def install
        bin.install "noted"
      end
    end
  end

  test do
    system "#{bin}/noted", "version"
  end
end
