# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noted < Formula
  desc "A CLI knowledge base to store and manage your notes efficiently"
  homepage "https://github.com/abdul-hamid-achik/noted"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.11.1/noted_0.11.1_darwin_amd64.tar.gz"
      sha256 "e6052adc89d577a348546fd8e2d6c49965d04274d669f6d375d0e97c07e8070b"

      define_method(:install) do
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.11.1/noted_0.11.1_darwin_arm64.tar.gz"
      sha256 "780d643258245e5789d8cb746183b5b3bb4fe808a69e2c9fab76e3ae2989155b"

      define_method(:install) do
        bin.install "noted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.11.1/noted_0.11.1_linux_amd64.tar.gz"
      sha256 "5317f33ebe3454eb39b4a0de82d4e9988eaab7e2ea9046f5180fef70b3a40d67"
      define_method(:install) do
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.11.1/noted_0.11.1_linux_arm64.tar.gz"
      sha256 "579ffd4f0626495e55fdffe6a49bdb44a6151a16de733f83f9b527bfb697bfae"
      define_method(:install) do
        bin.install "noted"
      end
    end
  end

  test do
    system "#{bin}/noted", "version"
  end
end
