# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noted < Formula
  desc "A CLI knowledge base to store and manage your notes efficiently"
  homepage "https://github.com/abdul-hamid-achik/noted"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.12.0/noted_0.12.0_darwin_amd64.tar.gz"
      sha256 "5932abbd5e9ebf68564ee1a30f8ff32f2d32318214b1f9b37d3a7fc094eeee80"

      define_method(:install) do
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.12.0/noted_0.12.0_darwin_arm64.tar.gz"
      sha256 "cd4326a7abf0216cfd6bf0cc24503db57b2839aa4df3633284bceb2299d45380"

      define_method(:install) do
        bin.install "noted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.12.0/noted_0.12.0_linux_amd64.tar.gz"
      sha256 "55589c7f59c3b79b314fda471b76e1fce24bd610ffa8606b3510952113f4e105"
      define_method(:install) do
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/noted/releases/download/v0.12.0/noted_0.12.0_linux_arm64.tar.gz"
      sha256 "a065dca65cc4e0aa6d9932bfe1887186e02908038aab7492079baf356817dde6"
      define_method(:install) do
        bin.install "noted"
      end
    end
  end

  test do
    system "#{bin}/noted", "version"
  end
end
