# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teak < Formula
  desc "Teak — A modern terminal code editor built with Go"
  homepage "https://github.com/abdul-hamid-achik/teak"
  version "0.10.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/teak/releases/download/v0.10.4/teak_0.10.4_Darwin_x86_64.tar.gz"
      sha256 "517349fb322d406e8aa5f7afb6da91ad954e06864cdce278f1cd3a82a59ea19c"

      define_method(:install) do
        bin.install "teak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/teak/releases/download/v0.10.4/teak_0.10.4_Darwin_arm64.tar.gz"
      sha256 "5257f37c07031c76ebc070a17738c277df8fc71af5d0705344cad699ab1a37bf"

      define_method(:install) do
        bin.install "teak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/teak/releases/download/v0.10.4/teak_0.10.4_Linux_x86_64.tar.gz"
      sha256 "8632ccfd46b5bd409095e73cee66022565ffc278cd7f7557242d3672236c7769"
      define_method(:install) do
        bin.install "teak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/teak/releases/download/v0.10.4/teak_0.10.4_Linux_arm64.tar.gz"
      sha256 "d680b2f81e6f0598a918cc53985ca607fa98da4e4e982e608b429811b6240195"
      define_method(:install) do
        bin.install "teak"
      end
    end
  end

  test do
    system "#{bin}/teak", "--version"
  end
end
