# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tvault < Formula
  desc "Dead simple secrets management CLI and MCP server"
  homepage "https://github.com/abdul-hamid-achik/tinyvault"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.11.1/tvault_0.11.1_darwin_amd64.tar.gz"
      sha256 "1b64223fd98ab7d352a18ac6dbd11d9c59060995158beb326c2e085eb720337f"

      define_method(:install) do
        bin.install "tvault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.11.1/tvault_0.11.1_darwin_arm64.tar.gz"
      sha256 "1487b4316517913f9605866b276c9042220d4faf53b4419bd2c2af62d504048c"

      define_method(:install) do
        bin.install "tvault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.11.1/tvault_0.11.1_linux_amd64.tar.gz"
      sha256 "54df1a48be41ac8a4843ab9ce081a2e778c67109f52c74b2efed6ae485d730f5"
      define_method(:install) do
        bin.install "tvault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.11.1/tvault_0.11.1_linux_arm64.tar.gz"
      sha256 "9121bb567b574ccd83fce240f32635c05ad358c00c943600de838b70235f6e49"
      define_method(:install) do
        bin.install "tvault"
      end
    end
  end

  test do
    system "#{bin}/tvault", "--version"
  end
end
