# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tvault < Formula
  desc "Dead simple secrets management CLI"
  homepage "https://tinyvault.dev"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.1.6/tvault_0.1.6_darwin_amd64.tar.gz"
      sha256 "a5a5363d3cb01a6949da32ca2fec66176f0ff262671f74527f86599f17cab69f"

      def install
        bin.install "tvault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.1.6/tvault_0.1.6_darwin_arm64.tar.gz"
      sha256 "ee0033c73ab06c4fc20925d62c687e632fc38f2c44e839792cac33edb309c820"

      def install
        bin.install "tvault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.1.6/tvault_0.1.6_linux_amd64.tar.gz"
      sha256 "28d8baeb43f56f023df98f862de82e45b07e3a3e005bfd673772e1eedf79bef1"
      def install
        bin.install "tvault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/tinyvault/releases/download/v0.1.6/tvault_0.1.6_linux_arm64.tar.gz"
      sha256 "f245039c802a37e7527408450ed3d30ce29ad42d29c99bb9978d17c825a4da42"
      def install
        bin.install "tvault"
      end
    end
  end

  test do
    system "#{bin}/tvault", "--version"
  end
end
