# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vecgrep < Formula
  desc "Local-first semantic code search powered by embeddings"
  homepage "https://github.com/abdul-hamid-achik/vecgrep"
  version "2.21.0"
  license "MIT"

  depends_on "ollama" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.21.0/vecgrep_2.21.0_darwin_amd64.tar.gz"
      sha256 "f7d17d27fa78eb8fac678e2c46e5a61743b0450caab00529a1ec16636eaca7ef"

      define_method(:install) do
        bin.install "vecgrep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.21.0/vecgrep_2.21.0_darwin_arm64.tar.gz"
      sha256 "a068796dc90b88ba921cb5e1ea3b5d9dbc5c6b613dc5ce32814f924a6d9cffdc"

      define_method(:install) do
        bin.install "vecgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.21.0/vecgrep_2.21.0_linux_amd64.tar.gz"
      sha256 "62ee442adcf50291274aeba56a2d0f566fd459cb5d8ca9f865ec029444609944"
      define_method(:install) do
        bin.install "vecgrep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.21.0/vecgrep_2.21.0_linux_arm64.tar.gz"
      sha256 "7cffc2fa2943915a8baa7cad7b9146777a04d7a8f75322256db18306c6d6a6b5"
      define_method(:install) do
        bin.install "vecgrep"
      end
    end
  end

  test do
    system "#{bin}/vecgrep", "--version"
  end
end
