# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vecgrep < Formula
  desc "Local-first semantic code search powered by embeddings"
  homepage "https://github.com/abdul-hamid-achik/vecgrep"
  version "2.7.1"
  license "MIT"

  depends_on "ollama" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.7.1/vecgrep_2.7.1_darwin_amd64.tar.gz"
      sha256 "d0aa52fe9a474fd40e8e62fd514293b16cba3cf1dba5235b477912433bc6f53a"

      define_method(:install) do
        bin.install "vecgrep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.7.1/vecgrep_2.7.1_darwin_arm64.tar.gz"
      sha256 "1ffbdd0989fb47140f36843092376a3173ab6aca811c53eff57722e73cf0b1e9"

      define_method(:install) do
        bin.install "vecgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.7.1/vecgrep_2.7.1_linux_amd64.tar.gz"
      sha256 "97d11b37997b7b8dea7ff63d387ece45603c4f141fd172e7210d427d499541a8"
      define_method(:install) do
        bin.install "vecgrep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.7.1/vecgrep_2.7.1_linux_arm64.tar.gz"
      sha256 "a00ba1a30b2e67637cb4e969bf47ef0c49de9aeb3987fd25513de7e1fe3fa0ef"
      define_method(:install) do
        bin.install "vecgrep"
      end
    end
  end

  test do
    system "#{bin}/vecgrep", "--version"
  end
end
