# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vecgrep < Formula
  desc "Local-first semantic code search powered by embeddings"
  homepage "https://github.com/abdul-hamid-achik/vecgrep"
  version "2.14.1"
  license "MIT"

  depends_on "ollama" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.14.1/vecgrep_2.14.1_darwin_amd64.tar.gz"
      sha256 "e10d0714798f555dec703fa8705527fcf50addb8f2ce789dce9636c4850aa55f"

      define_method(:install) do
        bin.install "vecgrep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.14.1/vecgrep_2.14.1_darwin_arm64.tar.gz"
      sha256 "86c578f03fd0c5054253750fa0bc752027984996fe7a6388a1d7e81680547a57"

      define_method(:install) do
        bin.install "vecgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.14.1/vecgrep_2.14.1_linux_amd64.tar.gz"
      sha256 "316a482196c4d0b503898a9138229ad83f12c4595c1a7515530c522f80f64c45"
      define_method(:install) do
        bin.install "vecgrep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/vecgrep/releases/download/v2.14.1/vecgrep_2.14.1_linux_arm64.tar.gz"
      sha256 "a460c0c7a8c269cdbfe1b1de8f2804ef31d5ab24f59b4fac4447e85337bcb66a"
      define_method(:install) do
        bin.install "vecgrep"
      end
    end
  end

  test do
    system "#{bin}/vecgrep", "--version"
  end
end
