# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veclite < Formula
  desc "SQLite for vectors. Embed anywhere, no servers, one file."
  homepage "https://github.com/abdul-hamid-achik/veclite"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.18.0/veclite_0.18.0_darwin_amd64.tar.gz"
      sha256 "d3458c974d000d3de8fe1e68e63749ed7212896d3d7810c13f1e6b5a5d041a04"

      define_method(:install) do
        bin.install "veclite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.18.0/veclite_0.18.0_darwin_arm64.tar.gz"
      sha256 "2621a194095fd611288d29885877287346bb9da13bbc30686736cc51e50688e5"

      define_method(:install) do
        bin.install "veclite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.18.0/veclite_0.18.0_linux_amd64.tar.gz"
      sha256 "253ae690ae8a9c90149bb8984ff8690d48ea2383fcaefca8b6351a8a1cd957ac"
      define_method(:install) do
        bin.install "veclite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.18.0/veclite_0.18.0_linux_arm64.tar.gz"
      sha256 "6160be55d84649143a107210909fb25bfb3eacb32fed98ab5965f4812aa43ef5"
      define_method(:install) do
        bin.install "veclite"
      end
    end
  end

  test do
    system "#{bin}/veclite", "version"
  end
end
