# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veclite < Formula
  desc "SQLite for vectors. Embed anywhere, no servers, one file."
  homepage "https://github.com/abdul-hamid-achik/veclite"
  version "0.22.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.22.0/veclite_0.22.0_darwin_amd64.tar.gz"
      sha256 "9e8150b4bcf99ad123311f04ab653534b7e11fb1585676c7b002dc6c10771192"

      define_method(:install) do
        bin.install "veclite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.22.0/veclite_0.22.0_darwin_arm64.tar.gz"
      sha256 "5bcd0d42240f2835b3592ac222ae7eda8e108bf12758239eee6279d481485fe2"

      define_method(:install) do
        bin.install "veclite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.22.0/veclite_0.22.0_linux_amd64.tar.gz"
      sha256 "da9aeef90871fbd650da507f1912f5eb9cf88c08bee5e93cd6bc1a9b1f3fb1e7"
      define_method(:install) do
        bin.install "veclite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.22.0/veclite_0.22.0_linux_arm64.tar.gz"
      sha256 "cf9597ad1268c3417f7fbf25e70056dc59cd116731864af4bc755e11e542ecf1"
      define_method(:install) do
        bin.install "veclite"
      end
    end
  end

  test do
    system "#{bin}/veclite", "version"
  end
end
