# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veclite < Formula
  desc "SQLite for vectors. Embed anywhere, no servers, one file."
  homepage "https://github.com/abdul-hamid-achik/veclite"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.2.0/veclite_0.2.0_darwin_amd64.tar.gz"
      sha256 "8d284c826d7cc8e9d44f967a9ebd6225a3a1bc879d350b269a1c0edfafefcf7c"

      def install
        bin.install "veclite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.2.0/veclite_0.2.0_darwin_arm64.tar.gz"
      sha256 "800e4f6c2a5c8fe29b48d19df77849775445ac9571d2a0889dc0d9279a74dd22"

      def install
        bin.install "veclite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.2.0/veclite_0.2.0_linux_amd64.tar.gz"
      sha256 "3b57bfb8dc4ae44a6ce9d501716f7962007301a9f92ed117ca6fdb74f52f5738"
      def install
        bin.install "veclite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/veclite/releases/download/v0.2.0/veclite_0.2.0_linux_arm64.tar.gz"
      sha256 "de86044afe35072a783534d0cdcdf1cb0b68ed3c7cb99c9bcdbe623141e85dc0"
      def install
        bin.install "veclite"
      end
    end
  end

  test do
    system "#{bin}/veclite", "version"
  end
end
